-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 13:38:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel_booking_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel_booking_system` ;

-- -----------------------------------------------------
-- Schema hotel_booking_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_booking_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotel_booking_system` ;

-- -----------------------------------------------------
-- Table `hotel_booking_system`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`role` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`role` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`account` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`account` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(350) NULL DEFAULT NULL,
  `Password` VARCHAR(20) NULL DEFAULT NULL,
  `Gender` TINYINT(1) NULL DEFAULT NULL,
  `Phone` CHAR(10) NULL DEFAULT NULL,
  `DoB` DATE NULL DEFAULT NULL,
  `Address` TEXT NULL DEFAULT NULL,
  `RoleID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE,
  INDEX `FK_RoleID` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `FK_RoleID`
    FOREIGN KEY (`RoleID`)
    REFERENCES `hotel_booking_system`.`role` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`hotel` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`hotel` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(350) NULL,
  `Phone` CHAR(10) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`booking` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`booking` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TotalPrice` INT NULL DEFAULT NULL,
  `BookingTime` DATETIME NULL DEFAULT NULL,
  `UpdatedTime` DATETIME NULL DEFAULT NULL,
  `CheckinTime` DATETIME NULL DEFAULT NULL,
  `CheckoutTime` DATETIME NULL DEFAULT NULL,
  `AccountID` INT NULL DEFAULT NULL,
  `HotelID` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_AccountID` (`AccountID` ASC) VISIBLE,
  INDEX `FK_HotelID_idx` (`HotelID` ASC) VISIBLE,
  CONSTRAINT `FK_AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `hotel_booking_system`.`account` (`Id`),
  CONSTRAINT `FK_HotelID_Booking`
    FOREIGN KEY (`HotelID`)
    REFERENCES `hotel_booking_system`.`hotel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`service` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`service` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Price` INT NULL DEFAULT NULL,
  `ServiceName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`bookingservice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`bookingservice` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`bookingservice` (
  `BookingID` INT NOT NULL,
  `ServiceID` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Number` INT NULL DEFAULT NULL,
  `Total` INT NULL DEFAULT NULL,
  PRIMARY KEY (`BookingID`, `ServiceID`, `Time`),
  INDEX `FK_ServiceID` (`ServiceID` ASC) VISIBLE,
  CONSTRAINT `FK_BookingID_BkService`
    FOREIGN KEY (`BookingID`)
    REFERENCES `hotel_booking_system`.`booking` (`Id`),
  CONSTRAINT `FK_ServiceID`
    FOREIGN KEY (`ServiceID`)
    REFERENCES `hotel_booking_system`.`service` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`paymentmethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`paymentmethod` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`paymentmethod` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Method` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`bill` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`bill` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Time` DATETIME NULL DEFAULT NULL,
  `Total` INT NULL DEFAULT NULL,
  `BookingID` INT NULL DEFAULT NULL,
  `PaymentMethodID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_PaymentMethodID` (`PaymentMethodID` ASC) VISIBLE,
  INDEX `FK_BookingID_Bill_idx` (`BookingID` ASC) VISIBLE,
  CONSTRAINT `FK_BookingID_Bill`
    FOREIGN KEY (`BookingID`)
    REFERENCES `hotel_booking_system`.`bookingservice` (`BookingID`),
  CONSTRAINT `FK_PaymentMethodID`
    FOREIGN KEY (`PaymentMethodID`)
    REFERENCES `hotel_booking_system`.`paymentmethod` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`roomtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`roomtype` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`roomtype` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoomType` VARCHAR(50) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`room` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`room` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(4) NULL DEFAULT NULL,
  `Price` INT NULL DEFAULT NULL,
  `Status` TINYINT NULL DEFAULT NULL,
  `RoomTypeID` INT NULL DEFAULT NULL,
  `HotelID` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_RoomTypeID` (`RoomTypeID` ASC) VISIBLE,
  INDEX `FK_HotelID_Room_idx` (`HotelID` ASC) VISIBLE,
  CONSTRAINT `FK_RoomTypeID`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `hotel_booking_system`.`roomtype` (`Id`),
  CONSTRAINT `FK_HotelID_Room`
    FOREIGN KEY (`HotelID`)
    REFERENCES `hotel_booking_system`.`hotel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotel_booking_system`.`bookingdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_booking_system`.`bookingdetails` ;

CREATE TABLE IF NOT EXISTS `hotel_booking_system`.`bookingdetails` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Price` INT NULL DEFAULT NULL,
  `RoomID` INT NULL DEFAULT NULL,
  `BookingID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_RoomID` (`RoomID` ASC) VISIBLE,
  INDEX `FK_BookingID_BkDetails` (`BookingID` ASC) VISIBLE,
  CONSTRAINT `FK_BookingID_BkDetails`
    FOREIGN KEY (`BookingID`)
    REFERENCES `hotel_booking_system`.`booking` (`Id`),
  CONSTRAINT `FK_RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `hotel_booking_system`.`room` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
